package model.helpers

object EntitiesBits {

  var WORLD_CATEGORY_BIT:Short = (1 << 0).toShort
  var HERO_CATEGORY_BIT:Short = (1 << 1).toShort
  var ENEMY_CATEGORY_BIT:Short = (1 << 2).toShort
  var ENEMY_PROJECTILE_CATEGORY_BIT:Short = (1 << 3).toShort
  var HERO_PROJECTILE_CATEGORY_BIT:Short = (1 << 4).toShort

  var WORLD_COLLISIONS_MASK:Short = (HERO_CATEGORY_BIT | ENEMY_CATEGORY_BIT | ENEMY_PROJECTILE_CATEGORY_BIT
    | HERO_PROJECTILE_CATEGORY_BIT).toShort
  var HERO_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT | ENEMY_PROJECTILE_CATEGORY_BIT).toShort
  var ENEMY_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT | HERO_PROJECTILE_CATEGORY_BIT).toShort
  var ENEMY_PROJECTILE_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT | HERO_CATEGORY_BIT).toShort
  var HERO_PROJECTILE_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT | HERO_CATEGORY_BIT).toShort

}
