package model.helpers

object EntitiesBits {

  var WORLD_CATEGORY_BIT:Short = 0x1
  var HERO_CATEGORY_BIT:Short = 0x2
  var ENEMY_CATEGORY_BIT:Short = 0x3
  var ENEMY_PROJECTILE_CATEGORY_BIT:Short = 0x4
  var HERO_PROJECTILE_CATEGORY_BIT:Short = 0x5

  var WORLD_COLLISIONS_MASK:Short = (HERO_CATEGORY_BIT | ENEMY_CATEGORY_BIT | ENEMY_PROJECTILE_CATEGORY_BIT | HERO_PROJECTILE_CATEGORY_BIT).toShort
  var HERO_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT | ENEMY_PROJECTILE_CATEGORY_BIT).toShort
  var ENEMY_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT | HERO_PROJECTILE_CATEGORY_BIT).toShort
  var ENEMY_PROJECTILE_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT).toShort
  var HERO_PROJECTILE_COLLISIONS_MASK:Short = (WORLD_CATEGORY_BIT).toShort

}
