package utils

object  SpritesConstants {

  val HERO_SPRITE_WIDTH: Int = 50
  val HERO_SPRITE_HEIGHT: Int = 37

  val ARROW_SPRITE_WIDTH: Int = 40
  val ARROW_SPRITE_HEIGHT: Int = 5

  val SKELETON_SPRITE_WIDTH: Int = 150
  val SKELETON_SPRITE_HEIGHT: Int = 150

  val SLIME_SPRITE_WIDTH: Int = 125
  val SLIME_SPRITE_HEIGHT: Int = 125

  val PACMAN_SPRITE_WIDTH: Int = 16
  val PACMAN_SPRITE_HEIGHT: Int = 16

  val WORM_SPRITE_WIDTH: Int = 90
  val WORM_SPRITE_HEIGHT: Int = 90

  val WIZARD_SPRITE_WIDTH: Int = 250
  val WIZARD_SPRITE_HEIGHT: Int = 250

  val FIREBALL_SPRITE_WIDTH: Int = 46
  val FIREBALL_SPRITE_HEIGHT: Int = 46

  val ENERGYBALL_SPRITE_WIDTH: Int = 128
  val ENERGYBALL_SPRITE_HEIGHT: Int = 128

  val REAPER_SPRITE_WIDTH: Int = 211
  val REAPER_SPRITE_HEIGHT: Int = 130

  val ITEM_SPRITE_WIDTH: Int = 32
  val ITEM_SPRITE_HEIGHT: Int = 34
  val ITEM_ENTITY_SPRITE_SIDE: Int = 15

  val PORTAL_SPRITE_WIDTH: Int = 64
  val PORTAL_SPRITE_HEIGHT: Int = 62

  val CHEST_SPRITE_WIDTH: Int = 64
  val CHEST_SPRITE_HEIGHT: Int = 68

  val DOOR_SPRITE_WIDTH: Int = 80
  val DOOR_SPRITE_HEIGHT: Int = 67

}
